### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by orhun** [chaosprint/asak#12]
I created an AUR package for asak here: https://aur.archlinux.org/packages/asak-git (builds from Git source)

I also would like to package it as a non-VCS package, so my question is are you planning to create releases on GitHub? 🐻

**Comment by chaosprint** [comment]
Yes. I just created one and will do it for the later release.

**Comment by orhun** [comment]
Thank you! I created another AUR package which builds from the latest stable version: https://aur.archlinux.org/packages/asak
